name: model-training
on:
  pull_request:
    types: [opened, reopened, edited, closed]
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install -r depend.txt
      - name: run training
        run: python train.py
      - name: save model
        uses: actions/upload-artifact@v2
        with:
          name: finalized_model_auto.sav
          path: /finalized_model_auto.sav
#test12345678
