name: model-training
on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:
  first_job:
    name: First job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
    #setup python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - run: pip install -r requierements.txt
      - run: python src/train.py

      - uses: actions/upload-artifact@v2
        with:
          name: finalized_model_auto.sav
          path: /finalized_model_auto.sav
#test123
